# Generated by Django 3.2.5 on 2021-07-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('quiz_true', models.CharField(max_length=100)),
                ('quiz_false', models.CharField(max_length=100)),
                ('quiz_explanation', models.CharField(max_length=300)),
                ('quiz_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password01', models.CharField(max_length=20)),
                ('password02', models.CharField(max_length=20)),
                ('profile_image', models.BinaryField(null=True)),
                ('email', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='a_user', serialize=False, to='main.user')),
                ('activity_img', models.BinaryField(null=True)),
                ('activity_content', models.CharField(max_length=400, null=True)),
                ('activity_date', models.DateTimeField()),
                ('activity_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shop_user', serialize=False, to='main.user')),
                ('addchallenge_id', models.IntegerField(null=True)),
                ('theme_id', models.IntegerField(null=True)),
                ('theme_name', models.CharField(max_length=45, null=True)),
                ('theme_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField()),
                ('challenge_name', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=45, null=True)),
                ('introduction', models.CharField(max_length=100, null=True)),
                ('challenge_start', models.DateTimeField()),
                ('term', models.DateTimeField()),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='main.user')),
                ('participants_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_id', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stp_user', serialize=False, to='main.user')),
                ('challenge_id', models.CharField(max_length=45)),
                ('activity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_id', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_mypage',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='q_user', serialize=False, to='main.user')),
                ('quiz_nonepass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_nonepass', to='main.quiz')),
                ('quiz_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_pass', to='main.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='p_user', serialize=False, to='main.user')),
                ('user_point', models.IntegerField()),
                ('point_log_name', models.ForeignKey(max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_log_name', to='main.shop')),
                ('point_log_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_log_price', to='main.shop')),
            ],
        ),
        migrations.CreateModel(
            name='N_badge',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nb_user', serialize=False, to='main.user')),
                ('n30_badge', models.BooleanField(default=True, null=True)),
                ('n50_badge', models.BooleanField(default=True, null=True)),
                ('n70_badge', models.BooleanField(default=True, null=True)),
                ('n100_badge', models.BooleanField(default=True, null=True)),
                ('badge_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_date', to='main.activity')),
                ('challenge', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='main.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_mypage',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='c_user', serialize=False, to='main.user')),
                ('challenge_ing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_ing', to='main.challenge')),
                ('challenge_past', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmychallenge_past', to='main.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge_Badge',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cb_user', serialize=False, to='main.user')),
                ('challenge_past', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbchallenge_past', to='main.challenge_mypage')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='challenge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atchallenge_id', to='main.challenge'),
        ),
    ]
