# Generated by Django 3.2.5 on 2021-07-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
