# Generated by Django 3.2.5 on 2021-07-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_challenge_challenge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(blank=True, upload_to='challengeapp/images/'),
        ),
    ]
