# Generated by Django 3.2.6 on 2021-08-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_challenge_challenge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='participants_id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='term',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_title',
            field=models.CharField(default='제목을 입력해주세요', max_length=45),
        ),
    ]
