# Generated by Django 3.2.6 on 2021-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210810_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_image',
            new_name='challenge_img',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='category',
        ),
        migrations.AddField(
            model_name='challenge',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main.Category'),
        ),
    ]
