# Generated by Django 3.2.6 on 2021-08-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210810_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_content',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_explanation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
